### ISSUE TITLE
Every thing is installed

### ISSUE THREAD

**Issue by DOGEPC** [Gravebot/Gravebot#222]
I have installed everything to run this bot on one of my servers and it cannaot stay up for 1/2 a secound.
The log is below:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle gravebot@3.0.0~prestart: gravebot@3.0.0
6 silly lifecycle gravebot@3.0.0~prestart: no script for prestart, continuing
7 info lifecycle gravebot@3.0.0~start: gravebot@3.0.0
8 verbose lifecycle gravebot@3.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle gravebot@3.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\User\Desktop\Gravebot\Gravebot-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\User\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\User\AppData\Local\Programs\Python\Python35\;C:\Users\User\AppData\Roaming\npm
10 verbose lifecycle gravebot@3.0.0~start: CWD: C:\Users\User\Desktop\Gravebot\Gravebot-master
11 silly lifecycle gravebot@3.0.0~start: Args: [ '/d /s /c', 'node index.js' ]
12 silly lifecycle gravebot@3.0.0~start: Returned: code: 1  signal: null
13 info lifecycle gravebot@3.0.0~start: Failed to exec start script
14 verbose stack Error: gravebot@3.0.0 start: `node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid gravebot@3.0.0
16 verbose cwd C:\Users\User\Desktop\Gravebot\Gravebot-master
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error gravebot@3.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the gravebot@3.0.0 start script 'node index.js'.

I am either in the wrong or this is a bug

**Comment by dustinblackman** [comment]
Gravebot is currently built against node 4, not node 6. While there should be no difference between the two, there still could be issues. Our windows support is also limited too. We've given what we could for an install guide for windows, but otherwise you're on your own.

`ELIFECYCLE` I've usually seen if the process is out of CPU resources to use. With a small community you usually don't see that kind of error with Gravebot. How big is your server?

**Comment by DOGEPC** [comment]
The server has a 3.5 ghz cpu and 8gb of ram with a 500gb ssd. not very big but packs a punch.

**Comment by dustinblackman** [comment]
That's far more then enough to run Gravebot. We run it with 450k users on much less. Try switching out the node versions, deleting your node_modules folder, and rerunning `npm i`. Some Windows users have reported having to run `npm run postinstall` after installation as npm doesn't fire it on it's own.

**Comment by DOGEPC** [comment]
thank you for the response, I thought my server was underperforming, I'll keep trying
