### ISSUE TITLE
Erorr cmd

### ISSUE THREAD

**Issue by malekksa505** [Gravebot/Gravebot#245]
C:\Users\xdrmalek\Desktop\Gravebot-master>node index.js
[2017-07-27 15:35:37] Booting...
module.js:471
    throw err;
    ^

Error: Cannot find module './dist'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\xdrmalek\Desktop\Gravebot-master\index.js:10
:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

C:\Users\xdrmalek\Desktop\Gravebot-master>

**Comment by malekksa505** [comment]
,  ???

**Comment by dustinblackman** [comment]
`npm run build`.
