### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by PaPiix** [Gravebot/Gravebot#256]
> node index.js

[2018-01-04 17:39:03] Booting...
module.js:557
    throw err;
    ^

Error: Cannot find module './dist'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Hussnain/Desktop/Gravebot-master/index.js:10:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gravebot@3.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gravebot@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Hussnain/.npm/_logs/2018-01-04T13_39_03_315Z-debug.log
MacBook-Pro:Gravebot-master Hussnain$

**Comment by dustinblackman** [comment]
The application requires you to compile first with `npm run build`.
