### ISSUE TITLE
Bot won't start

### ISSUE THREAD

**Issue by Imrenderman** [Gravebot/Gravebot#264]
I made sure to do all the steps for linux (Ubuntu 16.04) but I keep getting this error:

```
imr_enderman@wntrr-testserv:~/Gravebot$ npm start
> gravebot@3.0.0 start /home/imr_enderman/Gravebot
> node index.js
[2018-09-18 03:02:17] Booting...
module.js:550
    throw err;
    ^
Error: Cannot find module './dist'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/imr_enderman/Gravebot/index.js:10:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gravebot@3.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gravebot@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
imr_enderman@wntrr-testserv:~/Gravebot$
```

**Comment by ElijahPepe** [comment]
Same error for me. I think he gave up on Unix-based systems.
